baseurl = "http://preventa.tech/"
title = "Preventa Técnica | Google Cloud"
theme = "hugo-coder"
languagecode = "es"
defaultcontentlanguage = "es"

paginate = 20


[markup.highlight]
style = "github-dark"

[params]
  author = "Francisco Colomer"
  info = "Google Cloud Presales Engineer"
  description = "Diario de un preventa (desde las trincheras)."
  keywords = "preventa, preventa técnica, presales, presales engineer, google, google cloud, gcp, google cloud plaform. sales, ventas"
  avatarurl = "/images/avatar.png"
  #gravatar = "john.doe@example.com"

  favicon_32 = "/images/favicon-32x32.png"
  favicon_16 = "/images/favicon-16x16.png"
  
  since = 2023
  enableTwemoji = true

  
  colorScheme = "auto"
  hidecolorschemetoggle = false

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/fcolomer-dev"
[[params.social]]
  name = "LinkedIn"
  icon = "fa fa-linkedin fa-2x"
  weight = 2
  url = "https://www.linkedin.com/in/fcolomer/"
[[params.social]]
  name = "Stack Overflow"
  icon = "fa fa-stack-overflow fa-2x"
  weight = 3
  url = "https://stackoverflow.com/users/20122903/fcolomer"
[[params.social]]
  name = "Telegram"
  icon = "fa fa-telegram fa-2x"
  weight = 4
  url = "https://t.me/fcolomer"


# Menu links
[[menu.main]]
  name = "Bio"
  weight = 1
  url = "https://mnf.red/fcolomer"
  target = "_blank"
[[menu.main]]
  name = "Docs"
  weight = 2
  url = "https://docs.preventa.tech"


